### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by rogerzanoni** [INdT/Quasi-Engine#10]
Check and resolve all warnings, add Q_UNUSED macros if possible, etc

**Comment by mdkcore0** [comment]
There are some warnings that has been resolved on "tnoleto-coding-conventions", but you'll need some Qt5 version >= alpha

**Comment by tnoleto** [comment]
Warnings are gone with the patch:

commit 8b63995ec7ea7522febad0066bb753a927716555
Author: Tomaz Noleto tomaz.noleto@openbossa.org
Date:   Thu Apr 5 11:07:01 2012 -0400

```
Removed compilation warnings

Signed-off-by: Tomaz Noleto <tomaz.noleto@openbossa.org>
```
