### ISSUE TITLE
Examples won't run on Qt4

### ISSUE THREAD

**Issue by mdkcore0** [INdT/Quasi-Engine#11]
There are the need to change "import QtQuick 2.0" to "import QtQuick 1.1" when using Qt4.

If it is the correct behavior to follow (manually change the import) we must mention it on README.

**Comment by tnoleto** [comment]
The branch tnoleto-fix-examples has a patch which enables all the examples to run both either on Qt4 or Qt5. It uses a different "main-qt[4|5].qml" for each version. The app launcher code does basically the following:

1) Reads GameWindow.qml file contents
2) Checks the Qt version being used and prepends the correct QtQuick import version to the contents string
3) When main-qtX.qml file is loaded, creates dynamically an object from this string as a child of the main's toplevel item.

It is sort of a workaround, but does the trick.

**Comment by tnoleto** [comment]
By the way, that branch has also a patch which allows shadow build. It means that we can have on build tree for each Qt version at the same time. However, since we can export only one QML_IMPORT_PATH per environment, we need to run each build from different terminals.

**Comment by tnoleto** [comment]
Fixed by commit 3012b600bee63010d82025a112c5059c9523efa4
