### ISSUE TITLE
C++ class name should be consistent with corresponding exposed QML type

### ISSUE THREAD

**Issue by tnoleto** [INdT/Quasi-Engine#13]
Most of exposed QML types have different naming from their corresponding C++ class. There should be a consistent naming convention for those in order to avoid confusion. The current components are (C++ class name -> QML component name):

GameScene -> QuasiScene
GameItem -> QuasiEntity
SpriteItem -> QuasiSprite
SpriteAnimationItem -> QuasiAnimation
Box2DScene -> QuasiPhysicsScene
Box2DItem -> QuasiBody
Box2DDistanceJointItem -> QuasiDistanceJoint
Box2DMouseJointItem -> QuasiMouseJoint
GameLayers -> QuasiLayers
StaticLayer -> QuasiStaticLayer
AnimatedLayer -> QuasiAnimatedLayer
Viewport -> QuasiViewport

**Comment by rogerzanoni** [comment]
Fixed by d1c26ddc
