### ISSUE TITLE
Replace quasi engine collision detection system

### ISSUE THREAD

**Issue by rogerzanoni** [INdT/Quasi-Engine#4]
(...) with box2d collision detection system. Why not? It's pretty awesome and mine sucks.

**Comment by mdkcore0** [comment]
If box2d collision detection system has better performance, no problem to switch to it

**Comment by rogerzanoni** [comment]
Now, quasi will use box2d in all scene types and collision will be handled by box2d world object. Just waiting for resolution of issue #16 (Pull request)

**Comment by rogerzanoni** [comment]
Done in #17
